language: c

dist: xenial

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:

    # ARM GCC (Linux)

    - os: linux
      name: "ARM GCC"
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-gcc"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"
      addons:
        apt:
          packages:
            - ninja-build

    # Clang/LLVM + ARM GCC (Linux)

    - os: linux
      name: "Clang 8.0"
      env:
        - "C_COMPILER=clang-8"
        - "CXX_COMPILER=clang++-8"
        - "SIZE=llvm-size-8"
        - "OBJCOPY=llvm-objcopy-8"
        - "LINKER=lld-8"
        - "LLD=ld.lld-8"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - llvm-8
            - lld-8
            - ninja-build

    # Clang/LLVM (macOS)
    - os: osx
      osx_image: xcode10.1
      name: "Mac OSX LLVM 10"
      env:
        - "C_COMPILER=clang"
        - "CXX_COMPILER=clang++"
        - "SIZE=llvm-size"
        - "OBJCOPY=llvm-objcopy"
        - "LINKER=lld"
        - "LLD=ld.lld"
        - "LLVM_PKG=llvm@10"
      addons:
        homebrew:
          packages:
            - llvm@10
            - ninja
          update: true

    - os: osx
      osx_image: xcode10.1
      name: "Mac OSX LLVM 9"
      env:
        - "C_COMPILER=clang"
        - "CXX_COMPILER=clang++"
        - "SIZE=llvm-size"
        - "OBJCOPY=llvm-objcopy"
        - "LINKER=lld"
        - "LLD=ld.lld"
        - "LLVM_PKG=llvm@9"
      addons:
        homebrew:
          packages:
            - llvm@9
            - ninja
          update: true

    - os: osx
      osx_image: xcode10.1
      name: "Mac OSX LLVM 8"
      env:
        - "C_COMPILER=clang"
        - "CXX_COMPILER=clang++"
        - "SIZE=llvm-size"
        - "OBJCOPY=llvm-objcopy"
        - "LINKER=lld"
        - "LLD=ld.lld"
        - "LLVM_PKG=llvm@8"
      addons:
        homebrew:
          packages:
            - llvm@8
            - ninja
          update: true

script:
  - sh ci/script.sh
